definitions:
  Response-SumOutput:
    properties:
      data:
        $ref: '#/definitions/SumOutput'
      error:
        type: boolean
      message:
        type: string
    type: object
  Response-array_handler_FactResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/handler.FactResponse'
        type: array
      error:
        type: boolean
      message:
        type: string
    type: object
  Response-handler_FactResponse:
    properties:
      data:
        $ref: '#/definitions/handler.FactResponse'
      error:
        type: boolean
      message:
        type: string
    type: object
  Response-string:
    properties:
      data:
        type: string
      error:
        type: boolean
      message:
        type: string
    type: object
  SumInput:
    properties:
      num1:
        type: integer
      num2:
        type: integer
    required:
    - num1
    - num2
    type: object
  SumOutput:
    properties:
      result:
        type: integer
    type: object
  handler.FactResponse:
    properties:
      id:
        type: string
      text:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/facts/cats:
    get:
      consumes:
      - application/json
      description: Facts about cats
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response-array_handler_FactResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/Response-string'
      summary: Facts about cats
      tags:
      - Facts
  /api/v1/facts/dogs:
    get:
      consumes:
      - application/json
      description: Facts about dogs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response-handler_FactResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/Response-string'
      summary: Facts about dogs
      tags:
      - Facts
  /api/v1/sum:
    get:
      consumes:
      - application/json
      description: Handle the sum service using the query string
      parameters:
      - description: Number One
        in: query
        name: num1
        required: true
        type: integer
      - description: Number Two
        in: query
        name: num2
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response-SumOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response-string'
      summary: Handle the sum service using the query string
      tags:
      - sum
    post:
      consumes:
      - application/json
      description: Handle the sum service using the body
      parameters:
      - description: body input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/SumInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response-SumOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response-string'
      summary: Handle the sum service using the body
      tags:
      - sum
  /api/v1/sum/{num1}:
    get:
      consumes:
      - application/json
      description: Handle sum with first number in route path and second in query
        string
      parameters:
      - description: Number One
        in: path
        name: num1
        required: true
        type: integer
      - description: Number Two
        in: query
        name: num2
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response-SumOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response-string'
      summary: Handle sum with first number in route path and second in query string
      tags:
      - sum
  /api/v1/sum/{num1}/{num2}:
    get:
      consumes:
      - application/json
      description: Handle the sum service using the route path
      parameters:
      - description: Number One
        in: path
        name: num1
        required: true
        type: integer
      - description: Number Two
        in: path
        name: num2
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response-SumOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response-string'
      summary: Handle the sum service using the route path
      tags:
      - sum
  /heartbeat:
    get:
      consumes:
      - application/json
      description: Heartbeat returns a JSON response with the heartbeat status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response-string'
      summary: Heartbeat returns a JSON response with the heartbeat status
      tags:
      - heartbeat
swagger: "2.0"
